name: Deploy to Aruba

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Aruba
        uses: appleboy/ssh-action@master
        with:
          host: ftp.andreacaforio.it
          username: andrea
          key: parona2023
          script: |
            cd /path/to/your/website
            rm -rf * # Rimuovi i file esistenti
            scp -r build/* . # Copia i nuovi file build
